import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@autospace/ui/src/app/globals.css'
import { ApolloProvider } from '@autospace/network/src/config/apollo'
import { ClientProviders } from './ClientProviders'
import { Header } from '@autospace/ui/src/components/organisms/Header'
import { MenuItem } from '@autospace/util/types'
import { Container } from '@autospace/ui/src/components/atoms/Container'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Autospace',
  description: 'Generated by create next app',
}

const MENUITEMS: MenuItem[] = [
  { label: 'Search', href: '/search' },
  { label: 'Bookings', href: '/booking' },
  { label: 'About', href: '/about' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ClientProviders>
        <ApolloProvider>
          <body className={`${inter.className} bg-gray-25`}>
            <Header menuItems={MENUITEMS} />
            <Container>{children}</Container>
          </body>
        </ApolloProvider>
      </ClientProviders>
    </html>
  )
}
